%
%__________________________________________________________________________
%
% Matfile format for global rates
% note: this database is only used to built proff of the ocncept
%
%__________________________________________________________________________


clear all
clc
%format double
%
ConBbg = bloomberg;%(8194,'10.50.100.120') % too many connections, dun why, just need bloomberg and ok
StartDate = '1/1/1980'; % Start date
% -- Enter Today Date --
EndDate = '02/25/2015';
% -- Master Destination Path --
path = 'S:\Research\quant\JG\';

% Dowload Bloomberg History
TickerList = {'BFXSFVNS Index',...
'BFXSFVLS Index',...
'BFXSW5UE Index',...
'BXIICRUS Index',...
'BXIICCEU Index',...
'BXIIGELS Index',...
'BXIISWTUE Index',...
'BXIIXTDP Index',...
'BXIIXTYP Index',...
'BXIIVEUS Index',...
'BFXSMEUU Index',...
'SPDVIXP Index',...
'BEFSDVBE Index',...
'BEFSRDVX Index',...
'BEFSRCCE Index',...
'BEFSRCER Index',...
'BEFSRPSC Index',...
'DVSTXE Index',...
'DVSTXLE Index',...
'BCRIHGHA Index',...
'BCRIHGEA Index',...
'BCRIHGDA Index',...
'BXIIXTKP Index',...
'BCRITOMA Index',...
'BCCFDUAP Index',...
'BCCFDUBP Index',...
'BCCVCLAD Index',...
'BCCACS1P Index',...
'BCCAC06P Index',...
'BCCFCTRP Index',...
'BXIIXTCP Index',...
'BCCFBA3P Index',...
'BCCFBKAP Index',...
'BCCALT1P Index',...
'BCC3C3UP Index',...
'BCCFBKLP Index',...
'BXCS1496 Index',...
'BXIIBFCU Index',...
'BXIIRPN3 Index',...
'BXIIEP3G Index',...
'BXIIEXMA Index',...
'BXIISAGU Index',...
'BXIITSTP Index',...
'BXIITSP2 Index',...
'BXIIXTMP Index',...
'BXIIXTBP Index',...
'BXIIMDEG Index',...
'BXIIAIMS Index',...
'BXIIAIMA Index',...
'BXIIPMER Index',...
'BXIIPRGU Index',...
'BXIIMLUE Index',...
'EQCOMPBB Index',...
'BXIIOPUE Index',...
'BXIIAGUE Index',...
'BXIIMUEU Index',...
'BXIIMEEE Index',...
'BXIIMGEG Index',...
'BXIIMJEJ Index',...
'BXIIMWEU Index',...
'BXIICSEU Index',...
'BXIIESEE Index',...
'BXIIJSEJ Index',...
'BXIIASEU Index',...
'BXIIWILE Index',...
'RODIER Index',...
'BXIILUEU Index',...
'BXIILEEE Index',...
'BXIILGEG Index',...
'BXIILJEJ Index',...
'BXIIVUEU Index',...
'BXIIVUEM Index',...
'BXIIVEEE Index',...
'BXIIVGEG Index',...
'BXIIVJEJ Index',...
'BXIIVWEU Index',...
'BXIIKUEU Index',...
'BXIIKEEE Index',...
'BXIIKGEG Index',...
'BXIIKJEJ Index',...
'BXIIKWEU Index',...
'BXIICAEU Index',...
'BXIICEEE Index',...
'BXIICHEH Index',...
'BXIICUEG Index',...
'BXIICBEU Index',...
'BXIICYEU Index',...
'BXIICNEU Index',...
'BXIIRU10 Index',...
'BXIIRE10 Index',...
'BXIIRA10 Index',...
'BXIIRM15 Index',...
'BXIIUSLE Index',...
'BXIIEULE Index',...
'BXIIUKLE Index',...
'BXIIATMT Index',...
'SPMLPT Index',...
'BXIIOSMS Index',...
'BEFSWSUE Index',...
'BEFSWSEE Index',...
'BXIISSUE Index',...
'BXIISSEE Index',...
'BXIISSJE Index',...
'BXIISSHE Index',...
'BEFSEBWT Index',...
'BEFSEPWE Index',...
'BEFSTBWT Index',...
'BEFSTPWE Index',...
'SPVQDER Index',...
'SPVQMER Index',...
'SX5EVBE Index',...
'BXIIQMUE Index',...
'BXIIMPUE Index',...
'BXIIQWUE Index',...
'BEFSEBWS Index',...
'BEFSEDHS Index',...
'BEFSDHSP Index',...
'BEFSDHIW Index',...
'BEFSDHEM Index',...
'BXIISVUE Index',...
'BXIISVEE Index',...
'BEFSSVAE Index',...
'BEFSSVKE Index',...
'BEFSSVHE Index',...
'BEFSSVJE Index',...
'BEFSDHVO Index',...
'BEFSDHVS Index',...
'BEFSALSS Index',...
'BEFSALSM Index',...
'DVSTXAE Index',...
'BXIIVOUE Index',...
'BXIIVOEE Index',...
'BEFSVSEE Index',...
'BXIIXTAP Index',...
'BXIIXTEV Index',...
'BXIIXTVP Index',...
'BXIIXTEP Index',...
'BXIIMMUE Index',...
'BXIIMMEE Index',...
'BXIIMMGE Index',...
'BXIIMMJE Index',...
'BXIIASUE Index',...
'BXIIAVUE Index',...
'BXIIASEE Index',...
'BXIICMEU Index',...
'BXIIEMEE Index',...
'BXIIJMEJ Index',...
'BXIIAHEU Index',...
'BXIILMUE Index',...
'BXIILMEE Index',...
'BXIILMGE Index',...
'BXIILMJE Index',...
'BXIIVMUE Index',...
'BXIIVMME Index',...
'BXIIVMEE Index',...
'BXIIVMGE Index',...
'BXIIVMJE Index',...
'BXIIKMUE Index',...
'BXIIKMEE Index',...
'BXIIKMGE Index',...
'BXIIKMJE Index',...
'BXIIRRUD Index',...
'BXIIRRED Index',...
'BXIIRRMD Index',...
'BXIIUSSE Index',...
'BXIIEUSE Index',...
'BXIIUKSE Index',...
'BXIIMRU2 Index'};

for i=1:length(TickerList)
    AssetKey = i;    TickerName = TickerList(AssetKey);
    data = GetBbgHistMacro(ConBbg, TickerName, StartDate, EndDate); % No VWAP and No VOlume For rates
    % Save data under a text format with dynamic name
    FromBbg2Text_Macro(path, data, AssetKey) % return a text file called 'rates123.txt.
end