%
%__________________________________________________________________________
%
% Matfile format for global rates
% note: this database is only used to built proff of the ocncept
%
%__________________________________________________________________________


clear all
clc
%format double
%
ConBbg = bloomberg;%(8194,'10.50.100.120') % too many connections, dun why, just need bloomberg and ok
StartDate = '1/1/1980'; % Start date
% -- Enter Today Date --
EndDate = '9/26/2014';
%
% -- Master Destination Path --
path = 'S:\00 Individuals\Joel\CSVFiles\AsianGGR\';

% Dowload Bloomberg History
TickerList = {  'USGG30YR Index', 'USGG10YR Index','USGG5YR Index','USGG2YR Index','USGG3M Index', 'USGG1M Index',...
                'GECU30YR Index', 'GECU10YR Index','GECU5YR Index','GECU2YR Index','GECU3M Index', ... 
                'GJGB30 Index',  'GJGB10 Index', 'GJGB5 Index', 'GJGB2 Index', 'GJTB3MO Index', ...
                'GACGB10 Index', 'GACGB5 Index', 'GACGB2 Index', 'GACGB3M Index', ...
                'GNZGB10 Index',  'GNZGB5 Index','GNZGB2 Index', 'NDTB3M Curncy', ...
                'GCNY10YR Index',  'GCNY5YR Index', 'GCNY2YR Index', 'CNBI3MO Index',...
                'HKGG10Y Index', 'HKGG5Y Index', 'HKGG2Y Index', 'HKGG3M Index', 'HKGG1M Index',...
                'GVTW30YR Index', 'GVTW10YR Index',  'GVTW5YR Index', 'GVTW2YR Index', 'TAIBOR3M Index', 'TAIBOR1M Index',  ...
                'GVSK30YR Index', 'GVSK10YR Index', 'GVSK5YR Index',  'GVSK3MON Index',...
                'GIND10YR Index',  'GIND5YR Index', 'GIND2YR Index', 'GINTB3MO Index', ...
                'MASB30Y Index', 'MASB10Y Index', 'MASB5Y Index', 'MASB2Y Index', 'MASB3M Index', ...
                'MGIY10Y Index', 'MGIY5Y Index', 'MGIY2Y Index', 'KLIB1M Index', 'KLIB3M Index', ...
                'GIDN30YR Index', 'GIDN10YR Index', 'GIDN5YR Index', 'GIDN2YR Index','JIIN3M Index', 'JIIN1M Index', ...
                'PDSF10YR Index', 'PDSF5YR Index', 'PDSF2YR Index', 'PDSF3MO Index', 'PDSF1MO Index' , ...
                'GVTL10YR Index', 'GVTL5YR Index', 'GVTL2YR Index', 'TBDC3M Index', 'TBDC1M Index',}; 
for i=70:length(TickerList)
    AssetKey = i;    TickerName = TickerList(AssetKey);
    data = GetBbgHist(ConBbg, TickerName, 0,0, StartDate, EndDate); % No VWAP and No VOlume For rates
    % Save data under a text format with dynamic name
    FromBbg2Text_Rates(path, data, AssetKey) % return a text file called 'rates123.txt.
end

