%
%__________________________________________________________________________
%
% Matfile format for global rates
% note: this database is only used to built proff of the ocncept
%
%__________________________________________________________________________


clear all
clc
%format double
%
ConBbg = bloomberg;%(8194,'10.50.100.120') % too many connections, dun why, just need bloomberg and ok
StartDate = '1/1/1980'; % Start date
% -- Enter Today Date --
EndDate = '9/10/2014';
%
% -- Master Destination Path --
path = 'S:\00 Individuals\Joel\CSVFiles\';

% Dowload Bloomberg History
TickerList = {  'USSW10 Curncy', 'USSW9 Curncy','US0003M Index''USSW2 Curncy', 'USSW1 Curncy', 'USSW5 Curncy', 'USSW2 Curncy', 'USSW1 Curncy', ...
                'CDSW10 Curncy', 'CDSW9 Curncy', 'CDOR03 Index', 'CDSW2 Curncy', 'CDSW1 Curncy', 'CDSW5 Curncy', 'CDSW4 Curncy', 'CDSW1 Curncy', ...
                'EUSA10 Curncy', 'EUSA9 Curncy', 'EUR006M Index', 'EUSA2 Curncy', 'EUSA1 Curncy', 'EUSA2 Curncy', 'EUSA1 Curncy', 'EUSA1 Curncy', ...
                'BPSW10 Curncy','BPSW9 Curncy',  'BP0006M Index', 'BPSW2 Curncy','BPSW1 Curncy', 'BPSW5 Curncy', 'BPSW4 Curncy', 'BPSW1 Curncy',...
                'SFSW10 Curncy',  'SFSW9 Curncy', 'SF0006M Index',  'SFSW9 Curncy', ...
                'SKSW10 Curncy',  'SKSW9 Curncy',  'STIB3M Index', 'SKFS0101 BLC Curncy', ...
                'NKSW10 Curncy','NKSW9 Curncy',  'NIBOR6M Index', 'NKFS0101 BLC Curncy', ...
                'ADSWAP10 Curncy', 'ADSWAP9 Curncy', 'ADBB4M Index', 'ADSWAP2 Curncy', 'ADSWAP1 Curncy', 'ADSWAP5 Curncy',  'ADSWAP4 Curncy',  'ADSWAP1 Curncy', ...
                'NDSWAP10 Curncy','NDSWAP9 Curncy', 'NDBB3M Index', 'NDSWAP2 Curncy', 'NDSWAP1 Curncy',  'NDSWAP5 Curncy','NDSWAP4 Curncy', 'NDSWAP1 Curncy', ...
                'JYSW10 Curncy',  'JYSW9 Curncy', 'JY0006M Index', 'JYSW2 Curncy', 'JYSW1 Curncy', 'JYSW5 Curncy', 'JYSW4 Curncy','JYFS011 Curncy', ...
                'PZSW5 Curncy', 'PZSW4 Curncy', 'WIBR6M Index', ...
                'CKSW5 Curncy', 'CKSW4 Curncy',  'PRIB06M Index',  ...
                'HFSW5 Curncy', 'HFSW4 Curncy', 'BUBOR06M Index',  ...
                'ISSW5 Curncy',  'ISSW4 Curncy', 'TELBOR03 Index', ...
                'KWSWO5 Curncy', 'KWSWO4 Curncy',  'KWCDC Index',  'KWSWO4 Curncy',  'KWSWO4 Curncy', ...
                'MPSW10 Curncy', 'MPSW9 Curncy',  'MPSW5 Curncy',  'MPSW4 Curncy',  'MXIBTIIE Index', ...
                'IRSWM5 Curncy', 'IRSWM4 Curncy', 'MIFORIM6 Index', ...
                'MRSWQO5 Curncy','MRSWQO4 Curncy', 'KLIB3M Index', ...
                'SDSW5 Curncy', 'SDSW4Curncy', 'SORF6M Index', 'SDSW4 Curncy', ...
                'TYUSSW5 Curncy', 'TYUSSW4 Curncy', 'US0003M Index',  ...
                'SASW5 Curncy',  'SASW4 Curncy', 'JIBA3M Index', 'SAFS0101 BLC Curncy',  ...
                'BCSWNPD Curncy', 'BCSWMPD Curncy',  'BZDIOVRA Index', ...
                'NTSWO5 CMPN Curncy',  'NTSWO4 CMPN Curncy',  'TDSF90D Index',  ...
                'TBSWO5 CMPN Curncy', 'TBSWO4 CMPN Curncy',  'THFX6 Index'}; 
for i=1:length(TickerList)
    AssetKey = i;    TickerName = TickerList(AssetKey);
    data = GetBbgHist(ConBbg, TickerName, 0,0, StartDate, EndDate); % No VWAP and No VOlume For rates
    % Save data under a text format with dynamic name
    FromBbg2Text_Rates(path, data, AssetKey) % return a text file called 'rates123.txt.
end

