function createfigure(VertexNormals1, YData1, XData1, Vertices1, Faces1, VertexNormals2, YData2, Vertices2, XData2, YData3, XData3, XData4, XData5, XData6, YData4, YData5, YData6, YData7, YData8, YData9)
%CREATEFIGURE(VERTEXNORMALS1,YDATA1,XDATA1,VERTICES1,FACES1,VERTEXNORMALS2,YDATA2,VERTICES2,XDATA2,YDATA3,XDATA3,XDATA4,XDATA5,XDATA6,YDATA4,YDATA5,YDATA6,YDATA7,YDATA8,YDATA9)
%  VERTEXNORMALS1:  patch vertexnormals
%  YDATA1:  patch ydata
%  XDATA1:  patch xdata
%  VERTICES1:  patch vertices
%  FACES1:  patch faces
%  VERTEXNORMALS2:  patch vertexnormals
%  YDATA2:  patch ydata
%  VERTICES2:  patch vertices
%  XDATA2:  line xdata
%  YDATA3:  line ydata
%  XDATA3:  line xdata
%  XDATA4:  line xdata
%  XDATA5:  line xdata
%  XDATA6:  line xdata
%  YDATA4:  line ydata
%  YDATA5:  line ydata
%  YDATA6:  line ydata
%  YDATA7:  line ydata
%  YDATA8:  line ydata
%  YDATA9:  line ydata

%  Auto-generated by MATLAB on 13-Jun-2011 17:18:27

% Create figure
figure1 = figure('Renderer','zbuffer');

% Create axes
axes1 = axes('Parent',figure1,'YTick',zeros(1,0),'XTickLabel','',...
    'XTick',zeros(1,0),...
    'Position',[0.08864 0.1188 0.8409 0.75],...
    'LineWidth',2);
% Uncomment the following line to preserve the X-limits of the axes
% xlim([0 1]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim([0 1]);
box('on');

% Create patch
patch('Parent',axes1,'VertexNormals',VertexNormals1,'YData',YData1,...
    'XData',XData1,...
    'Vertices',Vertices1,...
    'Faces',Faces1,...
    'FaceColor',[0.88 0.88 0.88],...
    'FaceAlpha',0.2);

% Create patch
patch('Parent',axes1,'VertexNormals',VertexNormals2,'YData',YData2,...
    'XData',XData1,...
    'Vertices',Vertices2,...
    'Faces',Faces1,...
    'FaceColor',[0.753 0.753 0.753],...
    'FaceAlpha',0.2);

% Create line
line(XData2,YData3,'Parent',axes1,'LineWidth',2,...
    'Color',[0.3608 0.3608 0.3608]);

% Create line
line(XData3,YData3,'Parent',axes1,'LineWidth',2,...
    'Color',[0.3608 0.3608 0.3608]);

% Create line
line(XData4,YData3,'Parent',axes1,'LineWidth',2,...
    'Color',[0.3608 0.3608 0.3608]);

% Create line
line(XData5,YData3,'Parent',axes1,'LineWidth',2,...
    'Color',[0.3608 0.3608 0.3608]);

% Create line
line(XData6,YData3,'Parent',axes1,'LineWidth',2,...
    'Color',[0.3608 0.3608 0.3608]);

% Create line
line(XData2,YData3,'Parent',axes1,'Color',[1 1 1]);

% Create line
line(XData3,YData3,'Parent',axes1,'Color',[1 1 1]);

% Create line
line(XData4,YData3,'Parent',axes1,'Color',[1 1 1]);

% Create line
line(XData5,YData3,'Parent',axes1,'Color',[1 1 1]);

% Create line
line(YData3,YData4,'Parent',axes1,'Color',[0.3608 0.3608 0.3608]);

% Create line
line(YData3,YData5,'Parent',axes1,'Color',[0.3608 0.3608 0.3608]);

% Create line
line(YData3,YData6,'Parent',axes1,'Color',[0.3608 0.3608 0.3608]);

% Create line
line(YData3,YData7,'Parent',axes1,'Color',[0.3608 0.3608 0.3608]);

% Create line
line(YData3,YData8,'Parent',axes1,'Color',[0.3608 0.3608 0.3608]);

% Create line
line(YData3,YData9,'Parent',axes1,'Color',[0.3608 0.3608 0.3608]);

% Create text
text('Parent',axes1,'VerticalAlignment','bottom','String','Alpha',...
    'Position',[0.01081 0.6833 0],...
    'FontSize',9);

% Create text
text('Parent',axes1,'VerticalAlignment','bottom','String','1',...
    'Position',[0.2381 0.6833 0],...
    'FontSize',9);

% Create text
text('Parent',axes1,'VerticalAlignment','bottom','String','2',...
    'Position',[0.4313 0.6833 0],...
    'FontSize',9);

% Create text
text('Parent',axes1,'VerticalAlignment','bottom','String','3',...
    'Position',[0.6244 0.6833 0],...
    'FontSize',9);

% Create text
text('Parent',axes1,'VerticalAlignment','bottom',...
    'Position',[0.8176 0.6833 0],...
    'FontSize',9);

% Create text
text('Parent',axes1,'VerticalAlignment','bottom','String','Bravo',...
    'Position',[0.01081 0.5167 0],...
    'FontSize',9);

% Create text
text('Parent',axes1,'VerticalAlignment','bottom','String','4',...
    'Position',[0.2381 0.5167 0],...
    'FontSize',9);

% Create text
text('Parent',axes1,'VerticalAlignment','bottom','String','5',...
    'Position',[0.4313 0.5167 0],...
    'FontSize',9);

% Create text
text('Parent',axes1,'VerticalAlignment','bottom','String','6',...
    'Position',[0.6244 0.5167 0],...
    'FontSize',9);

% Create text
text('Parent',axes1,'VerticalAlignment','bottom',...
    'Position',[0.8176 0.5167 0],...
    'FontSize',9);

% Create text
text('Parent',axes1,'VerticalAlignment','bottom','String','Charlie',...
    'Position',[0.01081 0.35 0],...
    'FontSize',9);

% Create text
text('Parent',axes1,'VerticalAlignment','bottom','String','7',...
    'Position',[0.2381 0.35 0],...
    'FontSize',9);

% Create text
text('Parent',axes1,'VerticalAlignment','bottom','String','8',...
    'Position',[0.4313 0.35 0],...
    'FontSize',9);

% Create text
text('Parent',axes1,'VerticalAlignment','bottom','String','9',...
    'Position',[0.6244 0.35 0],...
    'FontSize',9);

% Create text
text('Parent',axes1,'VerticalAlignment','bottom','Position',[0.8176 0.35 0],...
    'FontSize',9);

% Create text
text('Parent',axes1,'VerticalAlignment','bottom',...
    'Position',[0.01081 0.1833 0],...
    'FontSize',9);

% Create text
text('Parent',axes1,'VerticalAlignment','bottom',...
    'Position',[0.2381 0.1833 0],...
    'FontSize',9);

% Create text
text('Parent',axes1,'VerticalAlignment','bottom',...
    'Position',[0.4313 0.1833 0],...
    'FontSize',9);

% Create text
text('Parent',axes1,'VerticalAlignment','bottom',...
    'Position',[0.6244 0.1833 0],...
    'FontSize',9);

% Create text
text('Parent',axes1,'VerticalAlignment','bottom',...
    'Position',[0.8176 0.1833 0],...
    'FontSize',9);

% Create text
text('Parent',axes1,'VerticalAlignment','bottom',...
    'Position',[0.01081 0.01667 0],...
    'FontSize',9);

% Create text
text('Parent',axes1,'VerticalAlignment','bottom',...
    'Position',[0.2381 0.01667 0],...
    'FontSize',9);

% Create text
text('Parent',axes1,'VerticalAlignment','bottom',...
    'Position',[0.4313 0.01667 0],...
    'FontSize',9);

% Create text
text('Parent',axes1,'VerticalAlignment','bottom',...
    'Position',[0.6244 0.01667 0],...
    'FontSize',9);

% Create text
text('Parent',axes1,'VerticalAlignment','bottom',...
    'Position',[0.8176 0.01667 0],...
    'FontSize',9);

% Create text
text('Parent',axes1,'VerticalAlignment','top','String','Param',...
    'Position',[0.1244 1 0],...
    'HorizontalAlignment','center',...
    'FontWeight','bold',...
    'FontSize',9);

% Create text
text('Parent',axes1,'VerticalAlignment','top','String','Lower Limit',...
    'Position',[0.3269 1 0],...
    'HorizontalAlignment','center',...
    'FontWeight','bold',...
    'FontSize',9);

% Create text
text('Parent',axes1,'VerticalAlignment','top','String','Upper Limit',...
    'Position',[0.5201 1 0],...
    'HorizontalAlignment','center',...
    'FontWeight','bold',...
    'FontSize',9);

% Create text
text('Parent',axes1,'VerticalAlignment','top','String','Initial Value',...
    'Position',[0.7133 1 0],...
    'HorizontalAlignment','center',...
    'FontWeight','bold',...
    'FontSize',9);

% Create text
text('Parent',axes1,'VerticalAlignment','top','String','Result',...
    'Position',[0.9065 1 0],...
    'HorizontalAlignment','center',...
    'FontSize',9);

% Create text
text('Parent',axes1,'VerticalAlignment','top','String','Use',...
    'Position',[-0.06757 1 0],...
    'FontWeight','bold',...
    'FontSize',9);

% uicontrol currently does not support code generation, enter 'doc uicontrol' for correct input syntax
% In order to generate code for uicontrol, you may use GUIDE. Enter 'doc guide' for more information

% uicontrol(...);

% uicontrol currently does not support code generation, enter 'doc uicontrol' for correct input syntax
% In order to generate code for uicontrol, you may use GUIDE. Enter 'doc guide' for more information

% uicontrol(...);

% uicontrol currently does not support code generation, enter 'doc uicontrol' for correct input syntax
% In order to generate code for uicontrol, you may use GUIDE. Enter 'doc guide' for more information

% uicontrol(...);

% uicontrol currently does not support code generation, enter 'doc uicontrol' for correct input syntax
% In order to generate code for uicontrol, you may use GUIDE. Enter 'doc guide' for more information

% uicontrol(...);

% uicontrol currently does not support code generation, enter 'doc uicontrol' for correct input syntax
% In order to generate code for uicontrol, you may use GUIDE. Enter 'doc guide' for more information

% uicontrol(...);

% uicontrol currently does not support code generation, enter 'doc uicontrol' for correct input syntax
% In order to generate code for uicontrol, you may use GUIDE. Enter 'doc guide' for more information

% uicontrol(...);

% uicontrol currently does not support code generation, enter 'doc uicontrol' for correct input syntax
% In order to generate code for uicontrol, you may use GUIDE. Enter 'doc guide' for more information

% uicontrol(...);

% uicontrol currently does not support code generation, enter 'doc uicontrol' for correct input syntax
% In order to generate code for uicontrol, you may use GUIDE. Enter 'doc guide' for more information

% uicontrol(...);

